//
//  TimeZoneManager.swift
//  DiamondXE
//
//  Created by iOS Developer on 21/06/24.
//

import Foundation
import UIKit

class TimeZoneMatcher {
    
    // Static list of time zones and their corresponding country codes
    private let timeZoneDict: [String: String] = [
        "America/Adak": "US",
            "America/Anchorage": "US",
            "America/Boise": "US",
            "America/Chicago": "US",
            "America/Denver": "US",
            "America/Detroit": "US",
            "America/Indiana/Indianapolis": "US",
            "America/Indiana/Knox": "US",
            "America/Indiana/Marengo": "US",
            "America/Indiana/Petersburg": "US",
            "America/Indiana/Tell_City": "US",
            "America/Indiana/Vevay": "US",
            "America/Indiana/Vincennes": "US",
            "America/Indiana/Winamac": "US",
            "America/Juneau": "US",
            "America/Kentucky/Louisville": "US",
            "America/Kentucky/Monticello": "US",
            "America/Los_Angeles": "US",
            "America/Menominee": "US",
            "America/Metlakatla": "US",
            "America/New_York": "US",
            "America/Nome": "US",
            "America/North_Dakota/Beulah": "US",
            "America/North_Dakota/Center": "US",
            "America/North_Dakota/New_Salem": "US",
            "America/Phoenix": "US",
            "America/Sitka": "US",
            "America/Yakutat": "US",
            "Pacific/Honolulu": "US",
            "Europe/London": "GB",
            "Asia/Dubai": "AE",
            "Asia/Singapore": "SG",
            "Pacific/Auckland": "NZ",
            "Pacific/Chatham": "NZ",
            "Asia/Calcutta": "IN",
            "Asia/Kolkata": "IN",
            "America/Atikokan": "CA",
            "America/Blanc": "CA",
            "America/Cambridge_Bay": "CA",
            "America/Creston": "CA",
            "America/Dawson": "CA",
            "America/Dawson_Creek": "CA",
            "America/Edmonton": "CA",
            "America/Fort_Nelson": "CA",
            "America/Glace_Bay": "CA",
            "America/Goose_Bay": "CA",
            "America/Halifax": "CA",
            "America/Inuvik": "CA",
            "America/Iqaluit": "CA",
            "America/Moncton": "CA",
            "America/Nipigon": "CA",
            "America/Pangnirtung": "CA",
            "America/Rainy_River": "CA",
            "America/Rankin_Inlet": "CA",
            "America/Regina": "CA",
            "America/Resolute": "CA",
            "America/St_Johns": "CA",
            "America/Swift_Current": "CA",
            "America/Thunder_Bay": "CA",
            "America/Toronto": "CA",
            "America/Vancouver": "CA",
            "America/Whitehorse": "CA",
            "America/Winnipeg": "CA",
            "America/Yellowknife": "CA",
            "Antarctica/Macquarie": "AU",
            "Australia/Adelaide": "AU",
            "Australia/Brisbane": "AU",
            "Australia/Broken_Hill": "AU",
            "Australia/Currie": "AU",
            "Australia/Darwin": "AU",
            "Australia/Eucla": "AU",
            "Australia/Hobart": "AU",
            "Australia/Lindeman": "AU",
            "Australia/Lord_Howe": "AU",
            "Australia/Melbourne": "AU",
            "Australia/Perth": "AU",
            "Australia/Sydney": "AU",
            "Asia/Kabul": "AF",
            "Europe/Mariehamn": "AX",
            "Europe/Tirane": "AL",
            "Africa/Algiers": "DZ",
            "Pacific/Pago_Pago": "AS",
            "Europe/Andorra": "AD",
            "Africa/Luanda": "AO",
            "America/Anguilla": "AI",
            "Antarctica/Casey": "AQ",
            "Antarctica/Davis": "AQ",
            "Antarctica/DumontDUrville": "AQ",
            "Antarctica/Mawson": "AQ",
            "Antarctica/McMurdo": "AQ",
            "Antarctica/Palmer": "AQ",
            "Antarctica/Rothera": "AQ",
            "Antarctica/Syowa": "AQ",
            "Antarctica/Troll": "AQ",
            "Antarctica/Vostok": "AQ",
            "America/Antigua": "AG",
            "America/Argentina/Buenos_Aires": "AR",
            "America/Argentina/Catamarca": "AR",
            "America/Argentina/Cordoba": "AR",
            "America/Argentina/Jujuy": "AR",
            "America/Argentina/La_Rioja": "AR",
            "America/Argentina/Mendoza": "AR",
            "America/Argentina/Rio_Gallegos": "AR",
            "America/Argentina/Salta": "AR",
            "America/Argentina/San_Juan": "AR",
            "America/Argentina/San_Luis": "AR",
            "America/Argentina/Tucuman": "AR",
            "America/Argentina/Ushuaia": "AR",
            "Asia/Yerevan": "AM",
            "America/Aruba": "AW",
            "Europe/Vienna": "AT",
            "Asia/Baku": "AZ",
            "America/Nassau": "BS",
            "Asia/Bahrain": "BH",
            "Asia/Dhaka": "BD",
            "America/Barbados": "BB",
            "Europe/Minsk": "BY",
            "Europe/Brussels": "BE",
            "America/Belize": "BZ",
            "Africa/Porto-Novo": "BJ",
            "Atlantic/Bermuda": "BM",
            "Asia/Thimphu": "BT",
            "America/La_Paz": "BO",
            "Europe/Sarajevo": "BA",
            "Africa/Gaborone": "BW",
            "Europe/Oslo": "BV",
            "America/Araguaina": "BR",
            "America/Bahia": "BR",
            "America/Belem": "BR",
            "America/Boa_Vista": "BR",
            "America/Campo_Grande": "BR",
            "America/Cuiaba": "BR",
            "America/Eirunepe": "BR",
            "America/Fortaleza": "BR",
            "America/Maceio": "BR",
            "America/Manaus": "BR",
            "America/Noronha": "BR",
            "America/Porto_Velho": "BR",
            "America/Recife": "BR",
            "America/Rio_Branco": "BR",
            "America/Santarem": "BR",
            "America/Sao_Paulo": "BR",
            "Indian/Chagos": "IO",
            "Asia/Brunei": "BN",
            "Europe/Sofia": "BG",
            "Africa/Ouagadougou": "BF",
            "Africa/Bujumbura": "BI",
            "Asia/Phnom_Penh": "KH",
            "Africa/Douala": "CM",
            "Atlantic/Cape_Verde": "CV",
            "America/Cayman": "KY",
            "Africa/Bangui": "CF",
            "Africa/Ndjamena": "TD",
            "America/Punta_Arenas": "CL",
            "America/Santiago": "CL",
            "Pacific/Easter": "CL",
            "Asia/Shanghai": "CN",
            "Asia/Urumqi": "CN",
            "Indian/Christmas": "CX",
            "Indian/Cocos": "CC",
            "America/Bogota": "CO",
            "Indian/Comoro": "KM",
            "Africa/Brazzaville": "CG",
            "Africa/Kinshasa": "CD",
            "Africa/Lubumbashi": "CD",
            "Pacific/Rarotonga": "CK",
            "America/Costa_Rica": "CR",
            "Africa/Abidjan": "CI",
            "Europe/Zagreb": "HR",
            "America/Havana": "CU",
            "Asia/Famagusta": "CY",
            "Asia/Nicosia": "CY",
            "Europe/Prague": "CZ",
            "Europe/Copenhagen": "DK",
            "Africa/Djibouti": "DJ",
            "America/Dominica": "DM",
            "America/Santo_Domingo": "DO",
            "Asia/Dili": "TL",
            "America/Guayaquil": "EC",
            "Pacific/Galapagos": "EC",
            "Africa/Cairo": "EG",
            "America/El_Salvador": "SV",
            "Africa/Malabo": "GQ",
            "Africa/Asmara": "ER",
            "Europe/Tallinn": "EE"
    ]
    
    private func getDeviceTimeZoneIdentifier() -> String {
           return TimeZone.current.identifier
       }
       
       // Method to find and return the matching time zone and country code
       func findAndPrintMatchingTimeZone() -> (String, String?) {
           let deviceTimeZoneIdentifier = getDeviceTimeZoneIdentifier()
           
           if let countryCode = timeZoneDict[deviceTimeZoneIdentifier] {
               return (deviceTimeZoneIdentifier, countryCode)
           } else {
               return (deviceTimeZoneIdentifier, nil)
           }
       }
}
